// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmf0weR8JPKAqiKBZ59u9YndMhQioH83U',
    appId: '1:169101867021:web:61e0bbd233a57da94e3d44',
    messagingSenderId: '169101867021',
    projectId: 'pushnotifications-57afa',
    authDomain: 'pushnotifications-57afa.firebaseapp.com',
    storageBucket: 'pushnotifications-57afa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkoNN9Pdxxag0OYZzwBHnClgAHToaquBY',
    appId: '1:169101867021:android:2d986410b06df7c04e3d44',
    messagingSenderId: '169101867021',
    projectId: 'pushnotifications-57afa',
    storageBucket: 'pushnotifications-57afa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAilUr6AAybCcqE7tkYnBLWYfFOo4DVRKM',
    appId: '1:169101867021:ios:7043dc1946ccf1624e3d44',
    messagingSenderId: '169101867021',
    projectId: 'pushnotifications-57afa',
    storageBucket: 'pushnotifications-57afa.firebasestorage.app',
    iosBundleId: 'com.example.pushnotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAilUr6AAybCcqE7tkYnBLWYfFOo4DVRKM',
    appId: '1:169101867021:ios:7043dc1946ccf1624e3d44',
    messagingSenderId: '169101867021',
    projectId: 'pushnotifications-57afa',
    storageBucket: 'pushnotifications-57afa.firebasestorage.app',
    iosBundleId: 'com.example.pushnotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmf0weR8JPKAqiKBZ59u9YndMhQioH83U',
    appId: '1:169101867021:web:b8f602118fae9a9c4e3d44',
    messagingSenderId: '169101867021',
    projectId: 'pushnotifications-57afa',
    authDomain: 'pushnotifications-57afa.firebaseapp.com',
    storageBucket: 'pushnotifications-57afa.firebasestorage.app',
  );
}
